In [1]:
import pandas as pd
import numpy as np

import plotly.graph_objects as go
import plotly.express as px


from dash import Dash, dcc, html
from dash import html

from dash.dependencies import Output, Input
from dash.exceptions import PreventUpdate

education = pd.read_csv("../Data/states_all.csv").assign(
    expenditure_per_student = lambda x: x["TOTAL_EXPENDITURE"] / x["GRADES_ALL_G"],
    above_avg_math8 = lambda x: np.where(x["AVG_MATH_8_SCORE"] > 278.6,'Above Avg', 'Below Avg')
)

education.tail()

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE,expenditure_per_student,above_avg_math8
1710,2019_VIRGINIA,VIRGINIA,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,247.0,287.0,224.0,262.0,NaN,Above Avg
1711,2019_WASHINGTON,WASHINGTON,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,240.0,286.0,220.0,266.0,NaN,Above Avg
1712,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,231.0,272.0,213.0,256.0,NaN,Below Avg
1713,2019_WISCONSIN,WISCONSIN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,242.0,289.0,220.0,267.0,NaN,Above Avg
1714,2019_WYOMING,WYOMING,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,246.0,286.0,227.0,265.0,NaN,Above Avg

### Labels & Values

In [2]:
dcc.Dropdown(
        id="X Column Picker",
        options=dict(zip(
            education.select_dtypes(include='number').columns,
            [column.title() for column in education.select_dtypes(include='number').columns],
        )),
        value="expenditure_per_student",
),

(Dropdown(options={'YEAR': 'Year', 'ENROLL': 'Enroll', 'TOTAL_REVENUE': 'Total_Revenue', 'FEDERAL_REVENUE': 'Federal_Revenue', 'STATE_REVENUE': 'State_Revenue', 'LOCAL_REVENUE': 'Local_Revenue', 'TOTAL_EXPENDITURE': 'Total_Expenditure', 'INSTRUCTION_EXPENDITURE': 'Instruction_Expenditure', 'SUPPORT_SERVICES_EXPENDITURE': 'Support_Services_Expenditure', 'OTHER_EXPENDITURE': 'Other_Expenditure', 'CAPITAL_OUTLAY_EXPENDITURE': 'Capital_Outlay_Expenditure', 'GRADES_PK_G': 'Grades_Pk_G', 'GRADES_KG_G': 'Grades_Kg_G', 'GRADES_4_G': 'Grades_4_G', 'GRADES_8_G': 'Grades_8_G', 'GRADES_12_G': 'Grades_12_G', 'GRADES_1_8_G': 'Grades_1_8_G', 'GRADES_9_12_G': 'Grades_9_12_G', 'GRADES_ALL_G': 'Grades_All_G', 'AVG_MATH_4_SCORE': 'Avg_Math_4_Score', 'AVG_MATH_8_SCORE': 'Avg_Math_8_Score', 'AVG_READING_4_SCORE': 'Avg_Reading_4_Score', 'AVG_READING_8_SCORE': 'Avg_Reading_8_Score', 'expenditure_per_student': 'Expenditure_Per_Student'}, value='expenditure_per_student', id='X Column Picker'),)

In [3]:
app = Dash(__name__)

app.layout = html.Div([
    html.H2(id="header"),
    dcc.Dropdown(
        id="X Column Picker",
        options=list(education.select_dtypes(include='number').columns),
        value="TOTAL_EXPENDITURE"
),
    dcc.Graph(id="graph"),
])

@app.callback(
    Output("header", "children"),
    Output("graph", "figure"),
    Input("X Column Picker", "value")
)

def plot_rev_scatter(x):
    if not x:
        raise PreventUpdate
    fig = px.scatter(
        education, 
        x=x, 
        y="AVG_MATH_8_SCORE",
        trendline="ols",
    )
    header = f"Math Score vs {x.title()}"
    return header, fig

if __name__ == "__main__":
    app.run(mode="inline", port=9271, debug=True)

### Multi Select Dropdowns

In [4]:
test = "HELLO"
test.title()

'Hello'

In [5]:
app = Dash(__name__)

app.layout = html.Div([
   dcc.Dropdown(
        id="filter",
        # options=education["STATE"].unique(),
        options=[{"label": state.title(), "value": state} for state in education["STATE"].unique()],
        value=["CALIFORNIA", "OREGON"],
        multi=True # pass multiple values into callback
    ),
    dcc.Graph(id="graph"),
])

@app.callback(
    Output('graph', 'figure'),
    Input("filter", "value"),
)

def plot_rev_scatter(state):
    fig = px.line(
        (education
         .query("STATE in @state and 1992 < YEAR < 2016")
         .reset_index()
        ), 
        x="YEAR", 
        y="TOTAL_EXPENDITURE",
        color="STATE",
        title = f"Expenditure Over Time, Selected States",
    ) 
    return fig


if __name__ == "__main__":
    app.run(mode="inline", port=2023, debug=True)

In [6]:
app = Dash(__name__)

app.layout= html.Div([
    dcc.Dropdown(
        id="filter",
        #styling the filter texts
        options=[{
            "label": html.Span(["Serene Republic of California"], style={"color": "powderblue", "font-size": 24}),
            "value":"CALIFORNIA"
        },
        {
            "label": html.Span(["Texas Zone of Anarchy"], style={"color": "brown", "font-size": 16}),
            "value": "TEXAS"
            
        }],
        value=["CALIFORNIA"],
        multi=True
    ),
    dcc.Graph(id="graph")
])
    
@app.callback(
    Output("graph", "figure"),
    Input("filter", "value")
)

def exp_line_chart(state):
    fig = px.line(
        (education
         .query("State in @state and 1992 < YEAR < 2016")
         .groupby(["YEAR", "STATE"])
         .sum()
         .reset_index()
        ),
        x="YEAR",
        y="TOTAL_EXPENDITURE",
        color="STATE",
        title = f"Expenditure Over Time, Selected States",
    )
    return fig

if __name__ == "__main__":
    app.run(mode="inline", debug=True, port=1234)

### Checklists

In [7]:
app = Dash(__name__)

app.layout = html.Div([
    dcc.Checklist(
        id="scores",
        options=[
            "AVG_MATH_4_SCORE",
            "AVG_MATH_8_SCORE",
            "AVG_READING_4_SCORE",
            "AVG_READING_8_SCORE"
        ],
        value=["AVG_MATH_4_SCORE"]
    ),
    dcc.Graph(id="graph")    
])

@app.callback(
    Output("graph", "figure"),
    Input("scores", "value")
)

def plot_hist(scores):
    fig = px.histogram(
        education,
        x=scores,
        barmode="overlay",
        title="Score Distribution"
    ).update_traces(opacity=.6)
    
    return fig

app.run(mode="inline", port=2084)

In [8]:
app = Dash(__name__)

app.layout = html.Div([
    dcc.Checklist(
        id="filter",
        options = ["CALIFORNIA", "TEXAS", "FLORIDA", "OREGON"],
#         options= [{"label": state.title(), "value": state} for state in education["STATE"].unique()] #note this is too many options, drop down may
        value=["CALIFORNIA", "TEXAS"]
    ),
    dcc.Graph(id="graph")    
])



@app.callback(
    Output("graph", "figure"),
    Input("filter", "value")
)


def exp_by_state(state):
    fig = px.line(
        (education
         .query("STATE in @state and 1992 < YEAR < 2016 ")
         .groupby(["YEAR", "STATE"])
         .sum()
         .reset_index()
        ),
        x="YEAR",
        y="TOTAL_EXPENDITURE",
        color="STATE",
        title="Expenditure Over Time, Selected States"
    )

    return fig

if __name__ == "__main__":
    app.run(mode="inline", port=4829)

### RadioItems (example of multiple filters)

In [9]:
app = Dash(__name__)

app.layout = html.Div([
    dcc.RadioItems(
        id="OLS Toggle",
        options=["Trendline On", "Trendline Off"],
        value="Trendline Off"
    ),
    dcc.Checklist(
        id="scores",
        options=[
            "AVG_MATH_4_SCORE",
            "AVG_MATH_8_SCORE",
            "AVG_READING_4_SCORE",
            "AVG_READING_8_SCORE"
        ],
        value=["AVG_MATH_4_SCORE"]
    ),
    dcc.Graph(id="graph"),
])

@app.callback(
    Output('graph', 'figure'),
    Input("OLS Toggle", "value"),
    Input("scores", "value")
)

def plot_rev_scatter(ols, scores):
    fig = px.scatter(
        education, 
        x="expenditure_per_student", 
        y=scores,
        trendline=None if ols == "Trendline Off" else "ols", # conditional logic
        title = "The Relationship Between Spending and Test Scores",
        )
    return fig

if __name__ == "__main__":
    app.run(mode="inline", debug=True, port=8274)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/computation/scope.py:233, in Scope.resolve(
    self=Scope(scope=['Timestamp',
 'datetime',
 'True',
... 'expenditure_per_student',
 'above_avg_math8']
),
    key='State',
    is_local=False
)
    232 if self.has_resolvers:
--> 233     return self.resolvers[key]
        self = Scope(scope=['Timestamp',
 'datetime',
 'True',
 'False',
 'list',
 'tuple',
 'inf',
 'Inf',
 '__name__',
 '__doc__',
 '__package__',
 '__loader__',
 '__spec__',
 '__builtin__',
 '__builtins__',
 '_ih',
 '_oh',
 '_dh',
 'In',
 'Out',
 'get_ipython',
 'exit',
 'quit',
 'open',
 '_',
 '__',
 '___',
 '__session__',
 '_i',
 '_ii',
 '_iii',
 '_i1',
 'pd',
 'np',
 'go',
 'px',
 'Dash',
 'dcc',
 'html',
 'Output',
 'Input',
 'PreventUpdate',
 'education',
 '_1',
 '_i2',
 '_2',
 '_i3',
 'app',
 'plot_rev_scatter',
 '_i4',
 'test',
 '_4',
 '_i5',
 '_i6',
 'exp_line_chart',
 'state']
, resolvers=['ilevel_0',
 'index',
 'clevel_0',
 'columns',
 'PRIMARY_KEY',
 'STATE',
 'YEAR',
 'ENROLL',
 'TOTAL_REVENUE',
 'FEDERAL_REVENUE',
 'STATE_REVENUE',
 'LOCAL_REVENUE',
 'TOTAL_EXPENDITURE',
 'INSTRUCTION_EXPENDITURE',
 'SUPPORT_SERVICES_EXPENDITURE',
 'OTHER_EXPENDITURE',
 'CAPITAL_OUTLAY_EXPENDITURE',
 'GRADES_PK_G',
 'GRADES_KG_G',
 'GRADES_4_G',
 'GRADES_8_G',
 'GRADES_12_G',
 'GRADES_1_8_G',
 'GRADES_9_12_G',
 'GRADES_ALL_G',
 'AVG_MATH_4_SCORE',
 'AVG_MATH_8_SCORE',
 'AVG_READING_4_SCORE',
 'AVG_READING_8_SCORE',
 'expenditure_per_student',
 'above_avg_math8']
)
        self.resolvers = DeepChainMap({'PRIMARY_KEY': 0             1992_ALABAMA
1              1992_ALASKA
2             1992_ARIZONA
3            1992_ARKANSAS
4          1992_CALIFORNIA
               ...
1710         2019_VIRGINIA
1711       2019_WASHINGTON
1712    2019_WEST_VIRGINIA
1713        2019_WISCONSIN
1714          2019_WYOMING
Name: PRIMARY_KEY, Length: 1715, dtype: object, 'STATE': 0             ALABAMA
1              ALASKA
2             ARIZONA
3            ARKANSAS
4          CALIFORNIA
            ...
1710         VIRGINIA
1711       WASHINGTON
1712    WEST_VIRGINIA
1713        WISCONSIN
1714          WYOMING
Name: STATE, Length: 1715, dtype: object, 'YEAR': 0       1992
1       1992
2       1992
3       1992
4       1992
        ...
1710    2019
1711    2019
1712    2019
1713    2019
1714    2019
Name: YEAR, Length: 1715, dtype: int64, 'ENROLL': 0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1710   NaN
1711   NaN
1712   NaN
1713   NaN
1714   NaN
Name: ENROLL, Length: 1715, dtype: float64, 'TOTAL_REVENUE': 0        2678885.0
1        1049591.0
2        3258079.0
3        1711959.0
4       26260025.0
           ...
1710           NaN
1711           NaN
1712           NaN
1713           NaN
1714           NaN
Name: TOTAL_REVENUE, Length: 1715, dtype: float64, 'FEDERAL_REVENUE': 0        304177.0
1        106780.0
2        297888.0
3        178571.0
4       2072470.0
          ...
1710          NaN
1711          NaN
1712          NaN
1713          NaN
1714          NaN
Name: FEDERAL_REVENUE, Length: 1715, dtype: float64, 'STATE_REVENUE': 0        1659028.0
1         720711.0
2        1369815.0
3         958785.0
4       16546514.0
           ...
1710           NaN
1711           NaN
1712           NaN
1713           NaN
1714           NaN
Name: STATE_REVENUE, Length: 1715, dtype: float64, 'LOCAL_REVENUE': 0        715680.0
1        222100.0
2       1590376.0
3        574603.0
4       7641041.0
          ...
1710          NaN
1711          NaN
1712          NaN
1713          NaN
1714          NaN
Name: LOCAL_REVENUE, Length: 1715, dtype: float64, 'TOTAL_EXPENDITURE': 0        2653798.0
1         972488.0
2        3401580.0
3        1743022.0
4       27138832.0
           ...
1710           NaN
1711           NaN
1712           NaN
1713           NaN
1714           NaN
Name: TOTAL_EXPENDITURE, Length: 1715, dtype: float64, 'INSTRUCTION_EXPENDITURE': 0        1481703.0
1         498362.0
2        1435908.0
3         964323.0
4       14358922.0
           ...
1710           NaN
1711           NaN
1712           NaN
1713           NaN
1714           NaN
Name: INSTRUCTION_EXPENDITURE, Length: 1715, dtype: float64, 'SUPPORT_SERVICES_EXPENDITURE': 0        735036.0
1        350902.0
2       1007732.0
3        483488.0
4       8520926.0
          ...
1710          NaN
1711          NaN
1712          NaN
1713          NaN
1714          NaN
Name: SUPPORT_SERVICES_EXPENDITURE, Length: 1715, dtype: float64, 'OTHER_EXPENDITURE': 0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1710   NaN
1711   NaN
1712   NaN
1713   NaN
1714   NaN
Name: OTHER_EXPENDITURE, Length: 1715, dtype: float64, 'CAPITAL_OUTLAY_EXPENDITURE': 0        174053.0
1         37451.0
2        609114.0
3        145212.0
4       2044688.0
          ...
1710          NaN
1711          NaN
1712          NaN
1713          NaN
1714          NaN
Name: CAPITAL_OUTLAY_EXPENDITURE, Length: 1715, dtype: float64, 'GRADES_PK_G': 0        8224.0
1        2371.0
2        2544.0
3         808.0
4       59067.0
         ...
1710        NaN
1711        NaN
1712        NaN
1713        NaN
1714        NaN
Name: GRADES_PK_G, Length: 1715, dtype: float64, 'GRADES_KG_G': 0        55460.0
1        10152.0
2        53497.0
3        33511.0
4       431763.0
          ...
1710         NaN
1711         NaN
1712         NaN
1713         NaN
1714         NaN
Name: GRADES_KG_G, Length: 1715, dtype: float64, 'GRADES_4_G': 0        57948.0
1         9748.0
2        55433.0
3        34632.0
4       418418.0
          ...
1710         NaN
1711         NaN
1712         NaN
1713         NaN
1714         NaN
Name: GRADES_4_G, Length: 1715, dtype: float64, 'GRADES_8_G': 0        58025.0
1         8789.0
2        49081.0
3        36011.0
4       363296.0
          ...
1710         NaN
1711         NaN
1712         NaN
1713         NaN
1714         NaN
Name: GRADES_8_G, Length: 1715, dtype: float64, 'GRADES_12_G': 0        41167.0
1         6714.0
2        37410.0
3        27651.0
4       270675.0
          ...
1710         NaN
1711         NaN
1712         NaN
1713         NaN
1714         NaN
Name: GRADES_12_G, Length: 1715, dtype: float64, 'GRADES_1_8_G': 0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1710   NaN
1711   NaN
1712   NaN
1713   NaN
1714   NaN
Name: GRADES_1_8_G, Length: 1715, dtype: float64, 'GRADES_9_12_G': 0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1710   NaN
1711   NaN
1712   NaN
1713   NaN
1714   NaN
Name: GRADES_9_12_G, Length: 1715, dtype: float64, 'GRADES_ALL_G': 0        731634.0
1        122487.0
2        673477.0
3        441490.0
4       5254844.0
          ...
1710          NaN
1711          NaN
1712          NaN
1713          NaN
1714          NaN
Name: GRADES_ALL_G, Length: 1715, dtype: float64, 'AVG_MATH_4_SCORE': 0       208.0
1         NaN
2       215.0
3       210.0
4       208.0
        ...
1710    247.0
1711    240.0
1712    231.0
1713    242.0
1714    246.0
Name: AVG_MATH_4_SCORE, Length: 1715, dtype: float64, 'AVG_MATH_8_SCORE': 0       252.0
1         NaN
2       265.0
3       256.0
4       261.0
        ...
1710    287.0
1711    286.0
1712    272.0
1713    289.0
1714    286.0
Name: AVG_MATH_8_SCORE, Length: 1715, dtype: float64, 'AVG_READING_4_SCORE': 0       207.0
1         NaN
2       209.0
3       211.0
4       202.0
        ...
1710    224.0
1711    220.0
1712    213.0
1713    220.0
1714    227.0
Name: AVG_READING_4_SCORE, Length: 1715, dtype: float64, 'AVG_READING_8_SCORE': 0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
        ...
1710    262.0
1711    266.0
1712    256.0
1713    267.0
1714    265.0
Name: AVG_READING_8_SCORE, Length: 1715, dtype: float64, 'expenditure_per_student': 0       3.627221
1       7.939520
2       5.050774
3       3.948044
4       5.164536
          ...
1710         NaN
1711         NaN
1712         NaN
1713         NaN
1714         NaN
Name: expenditure_per_student, Length: 1715, dtype: float64, 'above_avg_math8': 0       Below Avg
1       Below Avg
2       Below Avg
3       Below Avg
4       Below Avg
          ...
1710    Above Avg
1711    Above Avg
1712    Below Avg
1713    Above Avg
1714    Above Avg
Name: above_avg_math8, Length: 1715, dtype: object}, {'ilevel_0': 0          0
1          1
2          2
3          3
4          4
        ...
1710    1710
1711    1711
1712    1712
1713    1713
1714    1714
Length: 1715, dtype: int64, 'index': 0          0
1          1
2          2
3          3
4          4
        ...
1710    1710
1711    1711
1712    1712
1713    1713
1714    1714
Length: 1715, dtype: int64, 'clevel_0': PRIMARY_KEY                                      PRIMARY_KEY
STATE                                                  STATE
YEAR                                                    YEAR
ENROLL                                                ENROLL
TOTAL_REVENUE                                  TOTAL_REVENUE
FEDERAL_REVENUE                              FEDERAL_REVENUE
STATE_REVENUE                                  STATE_REVENUE
LOCAL_REVENUE                                  LOCAL_REVENUE
TOTAL_EXPENDITURE                          TOTAL_EXPENDITURE
INSTRUCTION_EXPENDITURE              INSTRUCTION_EXPENDITURE
SUPPORT_SERVICES_EXPENDITURE    SUPPORT_SERVICES_EXPENDITURE
OTHER_EXPENDITURE                          OTHER_EXPENDITURE
CAPITAL_OUTLAY_EXPENDITURE        CAPITAL_OUTLAY_EXPENDITURE
GRADES_PK_G                                      GRADES_PK_G
GRADES_KG_G                                      GRADES_KG_G
GRADES_4_G                                        GRADES_4_G
GRADES_8_G                                        GRADES_8_G
GRADES_12_G                                      GRADES_12_G
GRADES_1_8_G                                    GRADES_1_8_G
GRADES_9_12_G                                  GRADES_9_12_G
GRADES_ALL_G                                    GRADES_ALL_G
AVG_MATH_4_SCORE                            AVG_MATH_4_SCORE
AVG_MATH_8_SCORE                            AVG_MATH_8_SCORE
AVG_READING_4_SCORE                      AVG_READING_4_SCORE
AVG_READING_8_SCORE                      AVG_READING_8_SCORE
expenditure_per_student              expenditure_per_student
above_avg_math8                              above_avg_math8
dtype: object, 'columns': PRIMARY_KEY                                      PRIMARY_KEY
STATE                                                  STATE
YEAR                                                    YEAR
ENROLL                                                ENROLL
TOTAL_REVENUE                                  TOTAL_REVENUE
FEDERAL_REVENUE                              FEDERAL_REVENUE
STATE_REVENUE                                  STATE_REVENUE
LOCAL_REVENUE                                  LOCAL_REVENUE
TOTAL_EXPENDITURE                          TOTAL_EXPENDITURE
INSTRUCTION_EXPENDITURE              INSTRUCTION_EXPENDITURE
SUPPORT_SERVICES_EXPENDITURE    SUPPORT_SERVICES_EXPENDITURE
OTHER_EXPENDITURE                          OTHER_EXPENDITURE
CAPITAL_OUTLAY_EXPENDITURE        CAPITAL_OUTLAY_EXPENDITURE
GRADES_PK_G                                      GRADES_PK_G
GRADES_KG_G                                      GRADES_KG_G
GRADES_4_G                                        GRADES_4_G
GRADES_8_G                                        GRADES_8_G
GRADES_12_G                                      GRADES_12_G
GRADES_1_8_G                                    GRADES_1_8_G
GRADES_9_12_G                                  GRADES_9_12_G
GRADES_ALL_G                                    GRADES_ALL_G
AVG_MATH_4_SCORE                            AVG_MATH_4_SCORE
AVG_MATH_8_SCORE                            AVG_MATH_8_SCORE
AVG_READING_4_SCORE                      AVG_READING_4_SCORE
AVG_READING_8_SCORE                      AVG_READING_8_SCORE
expenditure_per_student              expenditure_per_student
above_avg_math8                              above_avg_math8
dtype: object})
        key = 'State'
    235 # if we're here that means that we have no locals and we also have
    236 # no resolvers

File ~/opt/anaconda3/lib/python3.8/collections/__init__.py:898, in ChainMap.__getitem__(
    self=DeepChainMap({'PRIMARY_KEY': 0             1992_...                  above_avg_math8
dtype: object}),
    key='State'
)
    897         pass
--> 898 return self.__missing__(key)            # support subclasses that define __missing__
        self = DeepChainMap({'PRIMARY_KEY': 0             1992_ALABAMA
1              1992_ALASKA
2             1992_ARIZONA
3            1992_ARKANSAS
4          1992_CALIFORNIA
               ...
1710         2019_VIRGINIA
1711       2019_WASHINGTON
1712    2019_WEST_VIRGINIA
1713        2019_WISCONSIN
1714          2019_WYOMING
Name: PRIMARY_KEY, Length: 1715, dtype: object, 'STATE': 0             ALABAMA
1              ALASKA
2             ARIZONA
3            ARKANSAS
4          CALIFORNIA
            ...
1710         VIRGINIA
1711       WASHINGTON
1712    WEST_VIRGINIA
1713        WISCONSIN
1714          WYOMING
Name: STATE, Length: 1715, dtype: object, 'YEAR': 0       1992
1       1992
2       1992
3       1992
4       1992
        ...
1710    2019
1711    2019
1712    2019
1713    2019
1714    2019
Name: YEAR, Length: 1715, dtype: int64, 'ENROLL': 0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1710   NaN
1711   NaN
1712   NaN
1713   NaN
1714   NaN
Name: ENROLL, Length: 1715, dtype: float64, 'TOTAL_REVENUE': 0        2678885.0
1        1049591.0
2        3258079.0
3        1711959.0
4       26260025.0
           ...
1710           NaN
1711           NaN
1712           NaN
1713           NaN
1714           NaN
Name: TOTAL_REVENUE, Length: 1715, dtype: float64, 'FEDERAL_REVENUE': 0        304177.0
1        106780.0
2        297888.0
3        178571.0
4       2072470.0
          ...
1710          NaN
1711          NaN
1712          NaN
1713          NaN
1714          NaN
Name: FEDERAL_REVENUE, Length: 1715, dtype: float64, 'STATE_REVENUE': 0        1659028.0
1         720711.0
2        1369815.0
3         958785.0
4       16546514.0
           ...
1710           NaN
1711           NaN
1712           NaN
1713           NaN
1714           NaN
Name: STATE_REVENUE, Length: 1715, dtype: float64, 'LOCAL_REVENUE': 0        715680.0
1        222100.0
2       1590376.0
3        574603.0
4       7641041.0
          ...
1710          NaN
1711          NaN
1712          NaN
1713          NaN
1714          NaN
Name: LOCAL_REVENUE, Length: 1715, dtype: float64, 'TOTAL_EXPENDITURE': 0        2653798.0
1         972488.0
2        3401580.0
3        1743022.0
4       27138832.0
           ...
1710           NaN
1711           NaN
1712           NaN
1713           NaN
1714           NaN
Name: TOTAL_EXPENDITURE, Length: 1715, dtype: float64, 'INSTRUCTION_EXPENDITURE': 0        1481703.0
1         498362.0
2        1435908.0
3         964323.0
4       14358922.0
           ...
1710           NaN
1711           NaN
1712           NaN
1713           NaN
1714           NaN
Name: INSTRUCTION_EXPENDITURE, Length: 1715, dtype: float64, 'SUPPORT_SERVICES_EXPENDITURE': 0        735036.0
1        350902.0
2       1007732.0
3        483488.0
4       8520926.0
          ...
1710          NaN
1711          NaN
1712          NaN
1713          NaN
1714          NaN
Name: SUPPORT_SERVICES_EXPENDITURE, Length: 1715, dtype: float64, 'OTHER_EXPENDITURE': 0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1710   NaN
1711   NaN
1712   NaN
1713   NaN
1714   NaN
Name: OTHER_EXPENDITURE, Length: 1715, dtype: float64, 'CAPITAL_OUTLAY_EXPENDITURE': 0        174053.0
1         37451.0
2        609114.0
3        145212.0
4       2044688.0
          ...
1710          NaN
1711          NaN
1712          NaN
1713          NaN
1714          NaN
Name: CAPITAL_OUTLAY_EXPENDITURE, Length: 1715, dtype: float64, 'GRADES_PK_G': 0        8224.0
1        2371.0
2        2544.0
3         808.0
4       59067.0
         ...
1710        NaN
1711        NaN
1712        NaN
1713        NaN
1714        NaN
Name: GRADES_PK_G, Length: 1715, dtype: float64, 'GRADES_KG_G': 0        55460.0
1        10152.0
2        53497.0
3        33511.0
4       431763.0
          ...
1710         NaN
1711         NaN
1712         NaN
1713         NaN
1714         NaN
Name: GRADES_KG_G, Length: 1715, dtype: float64, 'GRADES_4_G': 0        57948.0
1         9748.0
2        55433.0
3        34632.0
4       418418.0
          ...
1710         NaN
1711         NaN
1712         NaN
1713         NaN
1714         NaN
Name: GRADES_4_G, Length: 1715, dtype: float64, 'GRADES_8_G': 0        58025.0
1         8789.0
2        49081.0
3        36011.0
4       363296.0
          ...
1710         NaN
1711         NaN
1712         NaN
1713         NaN
1714         NaN
Name: GRADES_8_G, Length: 1715, dtype: float64, 'GRADES_12_G': 0        41167.0
1         6714.0
2        37410.0
3        27651.0
4       270675.0
          ...
1710         NaN
1711         NaN
1712         NaN
1713         NaN
1714         NaN
Name: GRADES_12_G, Length: 1715, dtype: float64, 'GRADES_1_8_G': 0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1710   NaN
1711   NaN
1712   NaN
1713   NaN
1714   NaN
Name: GRADES_1_8_G, Length: 1715, dtype: float64, 'GRADES_9_12_G': 0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1710   NaN
1711   NaN
1712   NaN
1713   NaN
1714   NaN
Name: GRADES_9_12_G, Length: 1715, dtype: float64, 'GRADES_ALL_G': 0        731634.0
1        122487.0
2        673477.0
3        441490.0
4       5254844.0
          ...
1710          NaN
1711          NaN
1712          NaN
1713          NaN
1714          NaN
Name: GRADES_ALL_G, Length: 1715, dtype: float64, 'AVG_MATH_4_SCORE': 0       208.0
1         NaN
2       215.0
3       210.0
4       208.0
        ...
1710    247.0
1711    240.0
1712    231.0
1713    242.0
1714    246.0
Name: AVG_MATH_4_SCORE, Length: 1715, dtype: float64, 'AVG_MATH_8_SCORE': 0       252.0
1         NaN
2       265.0
3       256.0
4       261.0
        ...
1710    287.0
1711    286.0
1712    272.0
1713    289.0
1714    286.0
Name: AVG_MATH_8_SCORE, Length: 1715, dtype: float64, 'AVG_READING_4_SCORE': 0       207.0
1         NaN
2       209.0
3       211.0
4       202.0
        ...
1710    224.0
1711    220.0
1712    213.0
1713    220.0
1714    227.0
Name: AVG_READING_4_SCORE, Length: 1715, dtype: float64, 'AVG_READING_8_SCORE': 0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
        ...
1710    262.0
1711    266.0
1712    256.0
1713    267.0
1714    265.0
Name: AVG_READING_8_SCORE, Length: 1715, dtype: float64, 'expenditure_per_student': 0       3.627221
1       7.939520
2       5.050774
3       3.948044
4       5.164536
          ...
1710         NaN
1711         NaN
1712         NaN
1713         NaN
1714         NaN
Name: expenditure_per_student, Length: 1715, dtype: float64, 'above_avg_math8': 0       Below Avg
1       Below Avg
2       Below Avg
3       Below Avg
4       Below Avg
          ...
1710    Above Avg
1711    Above Avg
1712    Below Avg
1713    Above Avg
1714    Above Avg
Name: above_avg_math8, Length: 1715, dtype: object}, {'ilevel_0': 0          0
1          1
2          2
3          3
4          4
        ...
1710    1710
1711    1711
1712    1712
1713    1713
1714    1714
Length: 1715, dtype: int64, 'index': 0          0
1          1
2          2
3          3
4          4
        ...
1710    1710
1711    1711
1712    1712
1713    1713
1714    1714
Length: 1715, dtype: int64, 'clevel_0': PRIMARY_KEY                                      PRIMARY_KEY
STATE                                                  STATE
YEAR                                                    YEAR
ENROLL                                                ENROLL

In [10]:
app = Dash(__name__)

app.layout = html.Div([
    dcc.RadioItems(
        id="aggfunc",
        options=["mean", "sum", "median"],
        value="mean"
    ),
    dcc.Graph(id="graph")
])

@app.callback(
    Output("graph", "figure"),
    Input("aggfunc", "value")
)
def plot_rev_metric(metric):
    fig = px.bar(
        (education
        .query("STATE in ['CALIFORNIA', 'OREGON', 'WASHINGTON', 'IDAHO'] and 1992 < YEAR < 2016")
        .groupby(["STATE"])
        .agg({"TOTAL_EXPENDITURE": metric})
        .reset_index()
        ),
        x="STATE",
        y="TOTAL_EXPENDITURE",
        text_auto=True,
        title = f" {metric.title()} Expenditure By State"
    )
    return fig

if __name__ == "__main__":
    app.run(mode="inline", debug=True)

### Sliders

In [11]:
app = Dash(__name__)

app.layout = html.Div([
    dcc.Slider(id="spend", min=0, max=30, step=5, value=15),
    dcc.Graph(id="graph"),
])

@app.callback(Output('graph', 'figure'), Input("spend", "value"))

def bar_chart(spending):
    fig = px.bar(
        (education
         .query("expenditure_per_student > @spending")
         .groupby("YEAR", as_index=False)
         .count()),
        x="YEAR",
        y="expenditure_per_student",
        title=f"States that spent over ${spending}K per student"      
    )
    fig.update_yaxes(title="COUNT", range=[0, 50])
    fig.update_xaxes(range=[1991, 2017])
    return fig

if __name__ == "__main__":
    app.run(mode="inline", debug=True, port=2323)

In [12]:
# range movable start and end points on the slider
app = Dash(__name__)

app.layout = html.Div([
    dcc.RangeSlider(id="spend", min=0, max=30, step=5, value=[10, 15]),
    dcc.Graph(id="graph"),
])

@app.callback(Output('graph', 'figure'), Input("spend", "value"))

def bar_chart(spending):
    fig = px.bar(
        (education
         .query("@spending[0] <= expenditure_per_student <= @spending[1]")
         .groupby("YEAR", as_index=False)
         .count()),
        x="YEAR",
        y="expenditure_per_student",
        title=f"States that spent between ${spending[0]}-{spending[1]}K per student"      
    )
    fig.update_yaxes(title="COUNT", range=[0, 50])
    fig.update_xaxes(range=[1991, 2017])
    return fig

if __name__ == "__main__":
    app.run(mode="inline", debug=True, port=2034)

In [13]:
app = Dash(__name__)

app.layout = html.Div([
   dcc.RangeSlider(
        id="score_slider",
        min=education.query("YEAR == 2013")["AVG_MATH_8_SCORE"].min(),
        max=education.query("YEAR == 2013")["AVG_MATH_8_SCORE"].max(),
        step=5,
        value=[270, 280]
    ),
    dcc.Graph(id="graph"),
])

@app.callback(
    Output('graph', 'figure'),
    Input("score_slider", "value"),
)

def plot_rev_scatter(score):
    df = (
        education
        .query("YEAR == 2013")
        .assign(
            score_cutoff =  lambda x: np.where(
                x["AVG_MATH_8_SCORE"].between(score[0], score[1]),
                'In Range', 
                'Out of Range'
            )
        )
    )
    fig = px.scatter(
        df,
        x="AVG_MATH_8_SCORE", 
        y="expenditure_per_student",
        color="score_cutoff",
        hover_name="STATE",
        title = f"Score and Expenditure vs. Threshold",
        )
    return fig


if __name__ == "__main__":
    app.run(mode="inline",debug=True, port=2934)

### Date Pickers

In [14]:
collisions = (
    pd.read_csv("../Data/NYC_Collisions.csv")
    .astype({"ACCIDENT_DATE": "datetime64[ns]"})
    .loc[:,["ACCIDENT_DATE", "BOROUGH", "COLLISION_ID"]]
    .groupby(["ACCIDENT_DATE", "BOROUGH"], as_index=False)
    .count()
    .rename(columns={
        "COLLISION_ID":"COLLISIONS", 
        "ACCIDENT_DATE":"DATE"})  
)

collisions.head()

        DATE        BOROUGH  COLLISIONS
0 2021-01-01          BRONX          28
1 2021-01-01       BROOKLYN          72
2 2021-01-01      MANHATTAN          23
3 2021-01-01         QUEENS          44
4 2021-01-01  STATEN ISLAND           8

In [15]:
from datetime import datetime
from datetime import date

app = Dash(__name__)


app.layout = html.Div([
    dcc.DatePickerSingle(
        id="date picker",
        min_date_allowed=collisions["DATE"].min(),
        max_date_allowed=collisions["DATE"].max(),
        initial_visible_month=collisions["DATE"].max(),
        date=collisions["DATE"].max(),
        display_format="YY-MMM-Do"
    ),
    dcc.Graph(id="graph")
])

@app.callback(Output("graph", "figure"), 
              [Input("date picker", "date")])
def plot_collisions_bar(date):
    fig = px.bar(
        collisions.loc[collisions["DATE"].eq(date)],
        x="COLLISIONS",
        y="BOROUGH",
        title=f"Traffic Accidents in NYC on {date}"
    )
    return fig

if __name__ == "__main__":
    app.run(mode="inline", port=8001, width="60%")

In [16]:
from datetime import datetime
from datetime import date

app = Dash(__name__)


app.layout = html.Div([
    dcc.DatePickerRange(
        id="date picker",
        min_date_allowed=collisions["DATE"].min(),
        max_date_allowed=collisions["DATE"].max(),
        initial_visible_month=collisions["DATE"].max(),
        start_date=collisions["DATE"].min(),
        end_date=date(2022,1,1),
        # display_format="YY-MMM-Do"
    ),
    dcc.Graph(id="graph")
])

@app.callback(Output("graph", "figure"), 
              [Input("date picker", "start_date"),
               Input("date picker", "end_date"),])
def plot_collisions_bar(start_date, end_date):
    fig = px.bar(
        (collisions
         .loc[collisions["DATE"].between(start_date, end_date)]
         .groupby("BOROUGH", as_index=False)
         .agg({"COLLISIONS": "sum"})
        )
        ,
        x="COLLISIONS",
        y="BOROUGH",
        title=f"Traffic Accidents in NYC between {start_date[:10]} and {end_date[:10]}"
    )
    return fig

if __name__ == "__main__":
    app.run(mode="inline", port=8001, width="60%")

### Multiple Input Callbacks
multiple inputs and outputs

In [17]:
app = Dash(__name__)

app.layout = html.Div([
    dcc.Dropdown(
        id="X Column Picker", 
        options=list(education.select_dtypes(include='number').columns),
        value="expenditure_per_student"
),
    dcc.Dropdown(
        id="Y Column Picker", 
        options=list(education.select_dtypes(include='number').columns),
        value="TOTAL_EXPENDITURE"
),
    dcc.Graph(id="graph"),
])

@app.callback(
    Output('graph', 'figure'),
    Input("X Column Picker", "value"),
    Input("Y Column Picker", "value")
)

def plot_rev_scatter(x, y):
    if not x:
        raise PreventUpdate
    if not y:
        raise PreventUpdate
    fig = px.scatter(
        education, 
        x=x, 
        y=y,
        trendline="ols",
#         marginal_x="box",
#         marginal_y="box",
#         color="STATE", # can be continous
#         size="YEAR", # can't be missing
        title = "State Vs. Federal Revenue",
        )
    #fig.update_traces(marker_color=cstolor)
    return fig


if __name__ == "__main__":
    app.run(mode="inline", 
                   height=600, 
                   width="80%", 
                   debug=True,
                   port=6165
                  )

In [ ]:
from datetime import datetime
from datetime import date

app = JupyterDash(__name__)


app.layout = html.Div([
    dcc.DatePickerRange(
        id="date picker",
        min_date_allowed=collisions["DATE"].min(),
        max_date_allowed=collisions["DATE"].max(),
        initial_visible_month=collisions["DATE"].max(),
        start_date=collisions["DATE"].min(),
        end_date=date(2022,1,1),
#         display_format="YY-MMM-Do"
),
    dcc.RadioItems(
        id="metric radio",
        options=["sum", "mean", "median", "min", "max"],
        value="sum"
),
    dcc.Dropdown(
        id="color dropdown",
        options=["red", "green", "blue"],
        value="blue"
),
    dcc.Graph(id="graph"),
])

@app.callback(
    Output("graph", "figure"), 
    [Input("date picker", "start_date"), Input("date picker", "end_date")],
    Input("metric radio", "value"),
    Input("color dropdown", "value"),
)
def plot_collisions_bar(start_date, end_date, metric, color): 
    
    df = collisions.loc[collisions["DATE"].between(start_date, end_date)]
    
    fig = px.bar(
        (df
         .groupby("BOROUGH", as_index=False)
         .agg({"COLLISIONS": metric})
        )
        ,
        x="COLLISIONS",
        y="BOROUGH",
        title=f"Traffic Accidents in NYC between {start_date[:10]} and {end_date[:10]}"
    ).update_traces(marker_color=color)
    
    
    return fig

if __name__ == "__main__":
    app.run_server(mode="inline", port=8001)

In [ ]:
app = JupyterDash(__name__)

app.layout = html.Div([
    html.H2(id="header"),
    dcc.Dropdown(
        id="X Column Picker",
        options=list(education.select_dtypes(include='number').columns),
        value="expenditure_per_student"
),
    dcc.Dropdown(
        id="Y Column Picker",
        options=list(education.select_dtypes(include='number').columns),
        value="TOTAL_EXPENDITURE"
),
    dcc.Graph(id="graph"),
])

@app.callback(
    Output('header', 'children'),
    Output('graph', 'figure'),
    Input("X Column Picker", "value"),
    Input("Y Column Picker", "value")
)

def plot_rev_scatter(x, y):
    if not x:
        raise PreventUpdate
    if not y:
        raise PreventUpdate
    fig = px.scatter(
        education, 
        x=x, 
        y=y,
        trendline="ols",
    )
    
    header = f"{x.title().replace('_', ' ')} Vs. {y.title().replace('_', ' ')}"
    return header, fig

if __name__ == "__main__":
    app.run_server(mode="inline", debug=True, port=2039)

In [19]:
from datetime import datetime
from datetime import date

app = Dash(__name__)


app.layout = html.Div([
    dcc.DatePickerRange(
        id="date picker",
        min_date_allowed=collisions["DATE"].min(),
        max_date_allowed=collisions["DATE"].max(),
        initial_visible_month=collisions["DATE"].max(),
        start_date=collisions["DATE"].min(),
        end_date=date(2022,1,1),
#         display_format="YY-MMM-Do"
),
    dcc.RadioItems(
        id="metric radio",
        options=["sum", "mean", "median", "min", "max"],
        value="sum"
),
    dcc.Dropdown(
        id="color dropdown",
        options=["red", "green", "blue"],
        value="blue"
),
    dcc.Graph(id="graph"),
    dcc.Graph(id="graph2")
])

@app.callback(
    Output("graph", "figure"), #first output
    Output("graph2", "figure"), #second output
    [Input("date picker", "start_date"), Input("date picker", "end_date")], # first input
    Input("metric radio", "value"), # second input
    Input("color dropdown", "value"), # third input
)
def plot_collisions_bar(start_date, end_date, metric, color): 
    
    df = collisions.loc[collisions["DATE"].between(start_date, end_date)]
    
    fig = px.bar(
        (df
         .groupby("BOROUGH", as_index=False)
         .agg({"COLLISIONS": metric})
        )
        ,
        x="COLLISIONS",
        y="BOROUGH",
        title=f"Traffic Accidents in NYC between {start_date[:10]} and {end_date[:10]}"
    ).update_traces(marker_color=color)
    
    fig2 = px.line(
        df,
        x="DATE",
        y="COLLISIONS",
        color="BOROUGH"
    )
    
    return fig , fig2

if __name__ == "__main__":
    app.run(mode="inline", port=8001)